"""Rolling-summary helpers.

When a user's conversation history grows past the soft threshold,
``maybe_summarize`` folds the oldest turns into a single leading system
message ("Earlier in this conversation: …") and keeps the most recent
turns verbatim. The summary itself is generated by a cheap LLM call
in ``summarize_turns``.

This used to live inside ``llm.py``; moved out as part of the Owela
migration so the application has a clean import boundary that doesn't
depend on the (now-deleted) old respond() loop. main.py + the Owela
``OngiiniMemoryProvider`` are the consumers.
"""

from __future__ import annotations

import logging
from typing import Any

from owela import Model, ModelRequest

from . import usage
from .config import settings
from .models.vllm_gemma import VLLMGemmaModel

log = logging.getLogger("ongiini.summary")

# Cheap, focused summariser. Output kept ≤ 150 tokens so the leading
# system message stays small enough that prefix-cache wins still
# dominate on the chat call that follows.
_SUMMARIZER_SYSTEM_PROMPT = (
    "You compress conversation history into 1–3 short sentences so a future "
    "AI assistant can continue helping the same user. Focus on:\n"
    "- stable facts the user shared (where they live, what they're working on, "
    "  their situation, what kinds of questions they ask)\n"
    "- topics the assistant has already covered, so we don't re-explain\n"
    "Write plain text, third person ('the user…'), no greeting, no markdown. "
    "When given a previous summary, fold its useful content into the new one — "
    "don't repeat or list both. Keep it tight."
)


SUMMARY_PREFIX = "Earlier in this conversation: "


# Module-level model adapter, constructed once. Going through the Owela
# adapter gives the summary the same output sanitising and request
# timeout as every other call. ``set_model`` lets the runtime share its
# adapter and tests inject a fake.
_model: Model = VLLMGemmaModel(settings.vllm_base_url, settings.vllm_model)
_SUMMARY_TIMEOUT_S = 30.0


def set_model(model: Model) -> None:
    global _model
    _model = model


async def summarize_turns(
    turns: list[dict[str, Any]],
    previous_summary: str = "",
    msisdn: str | None = None,
) -> str:
    """LLM-summarise a list of old turns. ``msisdn`` is for billing
    accounting — when None we skip the usage.record call (used by eval
    harnesses that don't want to pollute the live counter)."""
    if not turns:
        return previous_summary

    body = ""
    if previous_summary:
        body += f"Previous summary:\n{previous_summary}\n\n"
    body += "New turns to fold in:\n"
    for m in turns:
        role = m.get("role", "?")
        content = (m.get("content") or "")[:400]
        body += f"{role}: {content}\n"

    resp = await _model.complete(ModelRequest(
        messages=[
            {"role": "system", "content": _SUMMARIZER_SYSTEM_PROMPT},
            {"role": "user", "content": body},
        ],
        temperature=0.3,
        max_tokens=200,
        timeout_s=_SUMMARY_TIMEOUT_S,
    ))

    if msisdn:
        try:
            if resp.tokens_in or resp.tokens_out:
                usage.record(
                    msisdn, resp.tokens_in, resp.tokens_out,
                    used_search=False, kind="summary",
                )
        except Exception:
            pass    # billing is soft — never block the summary

    return (resp.content or "").strip()


async def load_history_folded(
    msisdn: str,
    *,
    load: Any,
    save: Any,
) -> list[dict[str, Any]]:
    """Load the user's history and, if it crossed the threshold, fold it
    AND persist the folded version.

    Persisting matters: before 2026-09-30 the folded history only went to
    the model, the stored file stayed long, and every later turn folded
    again — one extra model call per turn on long conversations, and a
    new summary at the head of the history each time, so vLLM's prefix
    cache never covered the history. Saved, the history grows from
    ``memory_keep_recent`` back to the threshold between folds and stays
    byte-stable (cacheable) in between.

    Call under the per-user lock.
    """
    history = load(msisdn)
    folded = await maybe_summarize(history, msisdn=msisdn)
    if folded is not history:
        try:
            save(msisdn, folded)
        except Exception as exc:                     # noqa: BLE001 — persistence is soft
            log.warning("saving folded history failed for %s: %s", msisdn, exc)
    return folded


async def maybe_summarize(
    history: list[dict[str, Any]],
    msisdn: str | None = None,
) -> list[dict[str, Any]]:
    """Fold oldest turns into a leading system summary when history is long.

    Triggered when ``len(history) > settings.memory_summary_threshold``.
    The last ``settings.memory_keep_recent`` entries stay verbatim;
    everything older is replaced with one system message prefixed with
    ``SUMMARY_PREFIX``. If a previous summary already sits at index 0,
    its content is folded into the new one rather than discarded.

    Returns the history unchanged when under threshold or when the LLM
    call fails to produce a usable summary — never raises, never loses
    data on the failure path.
    """
    if len(history) <= settings.memory_summary_threshold:
        return history

    if history and history[0].get("role") == "system":
        leading = (history[0].get("content") or "")
        if leading.startswith(SUMMARY_PREFIX):
            prev_summary = leading[len(SUMMARY_PREFIX):].strip()
        else:
            prev_summary = leading.strip()
        rest = history[1:]
    else:
        prev_summary = ""
        rest = history

    keep_n = settings.memory_keep_recent
    if len(rest) <= keep_n:
        return history
    to_summarize = rest[:-keep_n]
    keep = rest[-keep_n:]

    try:
        new_summary = await summarize_turns(to_summarize, prev_summary, msisdn=msisdn)
    except Exception:
        return history
    if not new_summary:
        return history

    return [
        {"role": "system", "content": SUMMARY_PREFIX + new_summary}
    ] + keep
