"""Rolling-summary helpers.

When a user's conversation history grows past the soft threshold,
``maybe_summarize`` folds the oldest turns into a single leading system
message ("Earlier in this conversation: …") and keeps the most recent
turns verbatim. The summary itself is generated by a cheap LLM call
in ``summarize_turns``.

This used to live inside ``llm.py``; moved out as part of the Owela
migration so the application has a clean import boundary that doesn't
depend on the (now-deleted) old respond() loop. main.py + the Owela
``OngiiniMemoryProvider`` are the consumers.
"""

from __future__ import annotations

import logging
from typing import Any

from openai import AsyncOpenAI

from . import usage
from .config import settings

log = logging.getLogger("ongiini.summary")

# Cheap, focused summariser. Output kept ≤ 150 tokens so the leading
# system message stays small enough that prefix-cache wins still
# dominate on the chat call that follows.
_SUMMARIZER_SYSTEM_PROMPT = (
    "You compress conversation history into 1–3 short sentences so a future "
    "AI assistant can continue helping the same user. Focus on:\n"
    "- stable facts the user shared (where they live, what they're working on, "
    "  their situation, what kinds of questions they ask)\n"
    "- topics the assistant has already covered, so we don't re-explain\n"
    "Write plain text, third person ('the user…'), no greeting, no markdown. "
    "When given a previous summary, fold its useful content into the new one — "
    "don't repeat or list both. Keep it tight."
)


SUMMARY_PREFIX = "Earlier in this conversation: "


# Module-level client. Constructed once; reused for every summarisation
# call.
_client = AsyncOpenAI(base_url=settings.vllm_base_url, api_key="not-needed")


async def summarize_turns(
    turns: list[dict[str, Any]],
    previous_summary: str = "",
    msisdn: str | None = None,
) -> str:
    """LLM-summarise a list of old turns. ``msisdn`` is for billing
    accounting — when None we skip the usage.record call (used by eval
    harnesses that don't want to pollute the live counter)."""
    if not turns:
        return previous_summary

    body = ""
    if previous_summary:
        body += f"Previous summary:\n{previous_summary}\n\n"
    body += "New turns to fold in:\n"
    for m in turns:
        role = m.get("role", "?")
        content = (m.get("content") or "")[:400]
        body += f"{role}: {content}\n"

    resp = await _client.chat.completions.create(
        model=settings.vllm_model,
        messages=[
            {"role": "system", "content": _SUMMARIZER_SYSTEM_PROMPT},
            {"role": "user", "content": body},
        ],
        temperature=0.3,
        max_tokens=200,
    )

    if msisdn:
        try:
            billable_in, completion, _cached = usage.billable_from_usage(resp.usage)
            if billable_in or completion:
                usage.record(
                    msisdn, billable_in, completion,
                    used_search=False, kind="summary",
                )
        except Exception:
            pass    # billing is soft — never block the summary

    return (resp.choices[0].message.content or "").strip()


async def maybe_summarize(
    history: list[dict[str, Any]],
    msisdn: str | None = None,
) -> list[dict[str, Any]]:
    """Fold oldest turns into a leading system summary when history is long.

    Triggered when ``len(history) > settings.memory_summary_threshold``.
    The last ``settings.memory_keep_recent`` entries stay verbatim;
    everything older is replaced with one system message prefixed with
    ``SUMMARY_PREFIX``. If a previous summary already sits at index 0,
    its content is folded into the new one rather than discarded.

    Returns the history unchanged when under threshold or when the LLM
    call fails to produce a usable summary — never raises, never loses
    data on the failure path.
    """
    if len(history) <= settings.memory_summary_threshold:
        return history

    if history and history[0].get("role") == "system":
        leading = (history[0].get("content") or "")
        if leading.startswith(SUMMARY_PREFIX):
            prev_summary = leading[len(SUMMARY_PREFIX):].strip()
        else:
            prev_summary = leading.strip()
        rest = history[1:]
    else:
        prev_summary = ""
        rest = history

    keep_n = settings.memory_keep_recent
    if len(rest) <= keep_n:
        return history
    to_summarize = rest[:-keep_n]
    keep = rest[-keep_n:]

    try:
        new_summary = await summarize_turns(to_summarize, prev_summary, msisdn=msisdn)
    except Exception:
        return history
    if not new_summary:
        return history

    return [
        {"role": "system", "content": SUMMARY_PREFIX + new_summary}
    ] + keep
