"""Phase D smoke: voice-note transcription end-to-end.

Two scenarios — both run faster-whisper for real (not mocked) so we
also confirm the model loaded and ffmpeg/CTranslate2 are wired up.

  case A — synthetic short clip generated by ffmpeg (1.5s of silence
           with a brief tone). Whisper should return a non-zero
           duration and a graceful empty/short transcript. The goal
           here is to confirm the pipeline survives audio that has
           no speech, not to test accuracy.

  case B — a 5-second 16kHz mono "spoken" sample generated by
           encoding "test test test" with espeak-ng if available
           (the system ffmpeg can pipe lavfi audio into Opus/OGG —
           the same shape WhatsApp produces).

If espeak-ng isn't in the container the second case falls back to
the silence case and just verifies the BinaryIO + ffmpeg path twice.

Run from inside the rebuilt webhook container:

    docker cp webhook/tests/audio_smoke.py ongiini-webhook:/data/audio_smoke.py
    docker exec ongiini-webhook python3 /data/audio_smoke.py
"""

from __future__ import annotations

import asyncio
import subprocess
import sys
import tempfile

sys.path.insert(0, "/app")

from app import audio  # noqa: E402


def _make_silence_ogg(duration_s: float = 1.5) -> bytes:
    """Generate <duration_s> of silence as OGG/Opus — matches WhatsApp's
    voice-note container/codec. Uses the system ffmpeg installed via
    the Dockerfile."""
    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as f:
        out_path = f.name
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", f"anullsrc=channel_layout=mono:sample_rate=16000",
        "-t", str(duration_s),
        "-c:a", "libopus", "-b:a", "32k",
        out_path,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    with open(out_path, "rb") as f:
        return f.read()


def _make_speechlike_ogg(text: str, voice: str = "en") -> bytes:
    """Render a short phrase to OGG/Opus via espeak-ng + ffmpeg.

    espeak-ng's robotic voice is far from natural speech, but
    large-v3-turbo is trained on enough varied data that it still
    transcribes the WORDS reliably — which is all the smoke needs.
    Raises FileNotFoundError if espeak-ng isn't installed.
    """
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        wav_path = f.name
    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as f:
        ogg_path = f.name
    subprocess.run(
        ["espeak-ng", "-v", voice, "-s", "150", "-w", wav_path, text],
        check=True, capture_output=True,
    )
    subprocess.run(
        ["ffmpeg", "-y", "-i", wav_path, "-c:a", "libopus", "-b:a", "32k", ogg_path],
        check=True, capture_output=True,
    )
    with open(ogg_path, "rb") as f:
        return f.read()


def _summarize(label: str, transcript: str, lang: str, duration: float) -> None:
    short_t = (transcript[:160] + "…") if len(transcript) > 160 else transcript
    print(f"  {label}: lang={lang!r:>10}  duration={duration:5.2f}s  "
          f"transcript_len={len(transcript)}")
    if transcript:
        print(f"    └─ {short_t!r}")


async def main() -> None:
    print("=== audio smoke ===")

    print("\n--- case A: 1.5s of silence (OGG/Opus, mimics WhatsApp container) ---")
    silence = _make_silence_ogg(1.5)
    print(f"  generated {len(silence)} bytes")
    transcript, lang, duration = await asyncio.to_thread(audio.transcribe, silence)
    _summarize("silence", transcript, lang, duration)
    assert duration > 0, f"expected non-zero duration, got {duration}"
    # transcript may be empty (no speech) or some Whisper hallucination —
    # both are acceptable. We only insist that transcribe() returned.

    # Case B - EN: real synthesised speech. Whisper should transcribe it
    # and the transcript should contain the salient nouns. We don't
    # require an exact match (espeak's robotic voice yields some word
    # variance) — just that the key content survived.
    print("\n--- case B (EN): 'I am a maize farmer in Oshakati' via espeak-ng ---")
    try:
        speech = _make_speechlike_ogg(
            "Hello, I am a maize farmer in Oshakati.", voice="en"
        )
        print(f"  generated {len(speech)} bytes")
        transcript, lang, duration = await asyncio.to_thread(audio.transcribe, speech)
        _summarize("EN speech", transcript, lang, duration)
        assert duration > 0, f"expected non-zero duration, got {duration}"
        low = transcript.lower()
        en_hits = sum(1 for word in ("maize", "farmer", "oshakati") if word in low)
        assert en_hits >= 2, (
            f"expected ≥2 of [maize, farmer, oshakati] in EN transcript, "
            f"got {en_hits}: {transcript!r}"
        )
        print(f"  ✓ transcript captured {en_hits}/3 expected keywords")
    except FileNotFoundError:
        print("  espeak-ng not installed — skipping EN content check")

    # Case C - AF: same flow with an Afrikaans phrase. espeak-ng's AF
    # voice is too robotic for Whisper to reliably reconstruct exact
    # words — it captures the phonemes but tokenises them oddly
    # (e.g. "Oshakati" → "osha kati"). Real WhatsApp speech is
    # natural-voice and works fine. So this case is a SOFT check:
    # we print the result for visual inspection and only assert that
    # Whisper produced *some* recognisable output rather than crashing.
    print("\n--- case C (AF): 'Ek is 'n mielie boer in Oshakati' via espeak-ng ---")
    try:
        speech_af = _make_speechlike_ogg(
            "Hallo, ek is 'n mielie boer in Oshakati.", voice="af"
        )
        print(f"  generated {len(speech_af)} bytes")
        transcript_af, lang_af, duration_af = await asyncio.to_thread(
            audio.transcribe, speech_af
        )
        _summarize("AF speech", transcript_af, lang_af, duration_af)
        assert duration_af > 0
        # Soft check: the Oshakati phonemes ('osha') must survive even
        # when tokenisation is off. Anything weaker than that suggests
        # the audio pipeline didn't actually decode the speech.
        assert "osha" in transcript_af.lower(), (
            f"expected 'osha' phonemes in AF transcript, got {transcript_af!r}"
        )
        print(f"  ✓ Oshakati phonemes survived (lang detected: {lang_af!r})")
    except FileNotFoundError:
        print("  espeak-ng not installed — skipping AF content check")

    print("\n=== smoke passed ===")


if __name__ == "__main__":
    asyncio.run(main())
