"""Phase D smoke: voice-note transcription end-to-end.

Two scenarios — both run faster-whisper for real (not mocked) so we
also confirm the model loaded and ffmpeg/CTranslate2 are wired up.

  case A — synthetic short clip generated by ffmpeg (1.5s of silence
           with a brief tone). Whisper should return a non-zero
           duration and a graceful empty/short transcript. The goal
           here is to confirm the pipeline survives audio that has
           no speech, not to test accuracy.

  case B — a 5-second 16kHz mono "spoken" sample generated by
           encoding "test test test" with espeak-ng if available
           (the system ffmpeg can pipe lavfi audio into Opus/OGG —
           the same shape WhatsApp produces).

If espeak-ng isn't in the container the second case falls back to
the silence case and just verifies the BinaryIO + ffmpeg path twice.

Run from inside the rebuilt webhook container:

    docker cp webhook/tests/audio_smoke.py ongiini-webhook:/data/audio_smoke.py
    docker exec ongiini-webhook python3 /data/audio_smoke.py
"""

from __future__ import annotations

import asyncio
import subprocess
import sys
import tempfile

sys.path.insert(0, "/app")

from app import audio  # noqa: E402


def _make_silence_ogg(duration_s: float = 1.5) -> bytes:
    """Generate <duration_s> of silence as OGG/Opus — matches WhatsApp's
    voice-note container/codec. Uses the system ffmpeg installed via
    the Dockerfile."""
    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as f:
        out_path = f.name
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", f"anullsrc=channel_layout=mono:sample_rate=16000",
        "-t", str(duration_s),
        "-c:a", "libopus", "-b:a", "32k",
        out_path,
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    with open(out_path, "rb") as f:
        return f.read()


def _make_speechlike_ogg() -> bytes:
    """If espeak-ng is available, render a short EN phrase to OGG/Opus.
    Otherwise raise FileNotFoundError so the caller can fall back."""
    text = "Hello, I am a small scale farmer in Oshakati."
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        wav_path = f.name
    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as f:
        ogg_path = f.name
    subprocess.run(
        ["espeak-ng", "-v", "en", "-s", "150", "-w", wav_path, text],
        check=True, capture_output=True,
    )
    subprocess.run(
        ["ffmpeg", "-y", "-i", wav_path, "-c:a", "libopus", "-b:a", "32k", ogg_path],
        check=True, capture_output=True,
    )
    with open(ogg_path, "rb") as f:
        return f.read()


def _summarize(label: str, transcript: str, lang: str, duration: float) -> None:
    short_t = (transcript[:160] + "…") if len(transcript) > 160 else transcript
    print(f"  {label}: lang={lang!r:>10}  duration={duration:5.2f}s  "
          f"transcript_len={len(transcript)}")
    if transcript:
        print(f"    └─ {short_t!r}")


async def main() -> None:
    print("=== audio smoke ===")

    print("\n--- case A: 1.5s of silence (OGG/Opus, mimics WhatsApp container) ---")
    silence = _make_silence_ogg(1.5)
    print(f"  generated {len(silence)} bytes")
    transcript, lang, duration = await asyncio.to_thread(audio.transcribe, silence)
    _summarize("silence", transcript, lang, duration)
    assert duration > 0, f"expected non-zero duration, got {duration}"
    # transcript may be empty (no speech) or some Whisper hallucination —
    # both are acceptable. We only insist that transcribe() returned.

    print("\n--- case B: synthesised speech (espeak-ng → OGG/Opus) ---")
    try:
        speech = _make_speechlike_ogg()
        print(f"  generated {len(speech)} bytes")
    except FileNotFoundError:
        print("  espeak-ng not installed — falling back to another silence clip")
        speech = _make_silence_ogg(2.5)

    transcript, lang, duration = await asyncio.to_thread(audio.transcribe, speech)
    _summarize("speech ", transcript, lang, duration)
    assert duration > 0, f"expected non-zero duration, got {duration}"

    print("\n=== smoke passed (no exceptions) ===")


if __name__ == "__main__":
    asyncio.run(main())
